package graphQL

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.80

import (
	"context"
	"strconv"

	"github.com/99designs/gqlgen/graphql"
	"github.com/BalkanID-University/vit-2026-capstone-internship-hiring-task-joel2607/middleware"
	"github.com/BalkanID-University/vit-2026-capstone-internship-hiring-task-joel2607/models"
)

// ID resolves the id field for the DeduplicatedContent type.
// It returns the unique identifier of the deduplicated content.
func (r *deduplicatedContentResolver) ID(ctx context.Context, obj *models.DeduplicatedContent) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

// CreatedAt resolves the createdAt field for the DeduplicatedContent type.
// It returns the timestamp indicating when the deduplicated content was first created.
func (r *deduplicatedContentResolver) CreatedAt(ctx context.Context, obj *models.DeduplicatedContent) (string, error) {
	return obj.CreatedAt.String(), nil
}

// UpdatedAt resolves the updatedAt field for the DeduplicatedContent type.
// It returns the timestamp indicating when the deduplicated content was last updated.
func (r *deduplicatedContentResolver) UpdatedAt(ctx context.Context, obj *models.DeduplicatedContent) (string, error) {
	return obj.UpdatedAt.String(), nil
}

// ReferenceCount resolves the referenceCount field for the DeduplicatedContent type.
// It returns the number of files that reference this deduplicated content.
func (r *deduplicatedContentResolver) ReferenceCount(ctx context.Context, obj *models.DeduplicatedContent) (int32, error) {
	return int32(obj.ReferenceCount), nil
}

// ID resolves the id field for the File type.
// It returns the unique identifier of the file.
func (r *fileResolver) ID(ctx context.Context, obj *models.File) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

// CreatedAt resolves the createdAt field for the File type.
// It returns the timestamp indicating when the file was created.
func (r *fileResolver) CreatedAt(ctx context.Context, obj *models.File) (string, error) {
	return obj.CreatedAt.String(), nil
}

// UpdatedAt resolves the updatedAt field for the File type.
// It returns the timestamp indicating when the file was last updated.
func (r *fileResolver) UpdatedAt(ctx context.Context, obj *models.File) (string, error) {
	return obj.UpdatedAt.String(), nil
}

// UserID resolves the userId field for the File type.
// It returns the unique identifier of the user who owns the file.
func (r *fileResolver) UserID(ctx context.Context, obj *models.File) (string, error) {
	return strconv.FormatUint(uint64(obj.UserID), 10), nil
}

// Size resolves the size field for the File type.
// It returns the size of the file in bytes.
func (r *fileResolver) Size(ctx context.Context, obj *models.File) (int32, error) {
	return int32(obj.Size), nil
}

// DeduplicationID resolves the deduplicationId field for the File type.
// It returns the identifier of the deduplicated content associated with this file.
func (r *fileResolver) DeduplicationID(ctx context.Context, obj *models.File) (string, error) {
	return strconv.FormatUint(uint64(obj.DeduplicationID), 10), nil
}

// DownloadCount resolves the downloadCount field for the File type.
// It returns the number of times the file has been downloaded.
func (r *fileResolver) DownloadCount(ctx context.Context, obj *models.File) (int32, error) {
	return int32(obj.DownloadCount), nil
}

// ParentFolderID resolves the parentFolderId field for the File type.
// It returns the identifier of the parent folder, or null if the file is in the root directory.
func (r *fileResolver) ParentFolderID(ctx context.Context, obj *models.File) (*string, error) {
	if obj.FolderID == nil {
		return nil, nil
	}
	id := strconv.FormatUint(uint64(*obj.FolderID), 10)
	return &id, nil
}

// ID resolves the id field for the FileSharing type.
// It returns the unique identifier of the file sharing record.
func (r *fileSharingResolver) ID(ctx context.Context, obj *models.FileSharing) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

// CreatedAt resolves the createdAt field for the FileSharing type.
// It returns the timestamp indicating when the file was shared.
func (r *fileSharingResolver) CreatedAt(ctx context.Context, obj *models.FileSharing) (string, error) {
	return obj.CreatedAt.String(), nil
}

// UpdatedAt resolves the updatedAt field for the FileSharing type.
// It returns the timestamp indicating when the file sharing record was last updated.
func (r *fileSharingResolver) UpdatedAt(ctx context.Context, obj *models.FileSharing) (string, error) {
	return obj.UpdatedAt.String(), nil
}

// FileID resolves the fileId field for the FileSharing type.
// It returns the unique identifier of the shared file.
func (r *fileSharingResolver) FileID(ctx context.Context, obj *models.FileSharing) (string, error) {
	return strconv.FormatUint(uint64(obj.FileID), 10), nil
}

// SharedWithUserID resolves the sharedWithUserId field for the FileSharing type.
// It returns the unique identifier of the user with whom the file is shared.
func (r *fileSharingResolver) SharedWithUserID(ctx context.Context, obj *models.FileSharing) (string, error) {
	return strconv.FormatUint(uint64(obj.SharedWithUserID), 10), nil
}

// ID resolves the id field for the Folder type.
// It returns the unique identifier of the folder.
func (r *folderResolver) ID(ctx context.Context, obj *models.Folder) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

// CreatedAt resolves the createdAt field for the Folder type.
// It returns the timestamp indicating when the folder was created.
func (r *folderResolver) CreatedAt(ctx context.Context, obj *models.Folder) (string, error) {
	return obj.CreatedAt.String(), nil
}

// UpdatedAt resolves the updatedAt field for the Folder type.
// It returns the timestamp indicating when the folder was last updated.
func (r *folderResolver) UpdatedAt(ctx context.Context, obj *models.Folder) (string, error) {
	return obj.UpdatedAt.String(), nil
}

// UserID resolves the userId field for the Folder type.
// It returns the unique identifier of the user who owns the folder.
func (r *folderResolver) UserID(ctx context.Context, obj *models.Folder) (string, error) {
	return strconv.FormatUint(uint64(obj.UserID), 10), nil
}

// ParentFolderID resolves the parentFolderId field for the Folder type.
// It returns the identifier of the parent folder, or null if the folder is in the root directory.
func (r *folderResolver) ParentFolderID(ctx context.Context, obj *models.Folder) (*string, error) {
	if obj.ParentFolderID == nil {
		return nil, nil
	}
	id := strconv.FormatUint(uint64(*obj.ParentFolderID), 10)
	return &id, nil
}

// Files is the resolver for the files field.
func (r *folderResolver) Files(ctx context.Context, obj *models.Folder) ([]*models.File, error) {
	var files []*models.File
	err := r.DB.Where("folder_id = ?", obj.ID).Find(&files).Error
	return files, err
}

// Folders is the resolver for the folders field.
func (r *folderResolver) Folders(ctx context.Context, obj *models.Folder) ([]*models.Folder, error) {
	var folders []*models.Folder
	err := r.DB.Where("parent_folder_id = ?", obj.ID).Find(&folders).Error
	return folders, err
}

// Register handles user registration.
// It accepts user registration details (username, email, password) and creates a new user account.
// Returns the newly created user object upon successful registration.
func (r *mutationResolver) Register(ctx context.Context, input models.RegisterInput) (*models.User, error) {
	user, err := r.AuthService.Register(input)
	if err != nil {
		return nil, err
	}
	return user, nil
}

// Login handles user authentication.
// It accepts a user's email and password, and if valid, returns an authentication response containing a token.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*models.AuthResponse, error) {
	token, user, err := r.AuthService.Login(email, password)
	if err != nil {
		return nil, err
	}
	return &models.AuthResponse{Token: token, User: user}, nil
}

// UploadFile is the resolver for the uploadFile field.
func (r *mutationResolver) UploadFile(ctx context.Context, file graphql.Upload, parentFolderID *string) (*models.File, error) {
	user, err := middleware.GetCurrentUser(ctx)
	if err != nil {
		return nil, err
	}
	return r.FileService.UploadFile(ctx, file, user, parentFolderID)
}

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, input models.NewFolder) (*models.Folder, error) {
	user, err := middleware.GetCurrentUser(ctx)
	if err != nil {
		return nil, err
	}
	return r.FileService.CreateFolder(ctx, input, user)
}

// UpdateFolder is the resolver for the updateFolder field.
func (r *mutationResolver) UpdateFolder(ctx context.Context, input models.UpdateFolder) (*models.Folder, error) {
	user, err := middleware.GetCurrentUser(ctx)
	if err != nil {
		return nil, err
	}
	return r.FileService.UpdateFolder(ctx, input, user)
}

// DeleteFolder is the resolver for the deleteFolder field.
func (r *mutationResolver) DeleteFolder(ctx context.Context, id string) (bool, error) {
	user, err := middleware.GetCurrentUser(ctx)
	if err != nil {
		return false, err
	}
	return r.FileService.DeleteFolder(ctx, id, user)
}

// UpdateFile is the resolver for the updateFile field.
func (r *mutationResolver) UpdateFile(ctx context.Context, input models.UpdateFile) (*models.File, error) {
	user, err := middleware.GetCurrentUser(ctx)
	if err != nil {
		return nil, err
	}
	return r.FileService.UpdateFile(ctx, input, user)
}

// DeleteFile is the resolver for the deleteFile field.
func (r *mutationResolver) DeleteFile(ctx context.Context, id string) (bool, error) {
	user, err := middleware.GetCurrentUser(ctx)
	if err != nil {
		return false, err
	}
	return r.FileService.DeleteFile(ctx, id, user)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	return middleware.GetCurrentUser(ctx)
}

// Folder is the resolver for the folder field.
func (r *queryResolver) Folder(ctx context.Context, id string) (*models.Folder, error) {
	user, err := middleware.GetCurrentUser(ctx)
	if err != nil {
		return nil, err
	}
	return r.FileService.GetFolder(ctx, id, user)
}

// Root is the resolver for the root field.
func (r *queryResolver) Root(ctx context.Context) (*models.Root, error) {
	user, err := middleware.GetCurrentUser(ctx)
	if err != nil {
		return nil, err
	}
	return r.FileService.GetRoot(ctx, user)
}

// ID resolves the id field for the User type.
// It returns the unique identifier of the user.
func (r *userResolver) ID(ctx context.Context, obj *models.User) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

// CreatedAt resolves the createdAt field for the User type.
// It returns the timestamp indicating when the user account was created.
func (r *userResolver) CreatedAt(ctx context.Context, obj *models.User) (string, error) {
	return obj.CreatedAt.String(), nil
}

// UpdatedAt resolves the updatedAt field for the User type.
// It returns the timestamp indicating when the user account was last updated.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *models.User) (string, error) {
	return obj.UpdatedAt.String(), nil
}

// StorageQuotaMb is the resolver for the storageQuotaMB field.
func (r *userResolver) StorageQuotaMb(ctx context.Context, obj *models.User) (int32, error) {
	return int32(obj.StorageQuotaMB), nil
}

// UsedStorageMb is the resolver for the usedStorageMB field.
func (r *userResolver) UsedStorageMb(ctx context.Context, obj *models.User) (int32, error) {
	return int32(obj.UsedStorageMB), nil
}

// APIRateLimit resolves the apiRateLimit field for the User type.
// It returns the maximum number of API requests the user can make per minute.
func (r *userResolver) APIRateLimit(ctx context.Context, obj *models.User) (int32, error) {
	return int32(obj.APIRateLimit), nil
}

// DeduplicatedContent returns DeduplicatedContentResolver implementation.
func (r *Resolver) DeduplicatedContent() DeduplicatedContentResolver {
	return &deduplicatedContentResolver{r}
}

// File returns FileResolver implementation.
func (r *Resolver) File() FileResolver { return &fileResolver{r} }

// FileSharing returns FileSharingResolver implementation.
func (r *Resolver) FileSharing() FileSharingResolver { return &fileSharingResolver{r} }

// Folder returns FolderResolver implementation.
func (r *Resolver) Folder() FolderResolver { return &folderResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type deduplicatedContentResolver struct{ *Resolver }
type fileResolver struct{ *Resolver }
type fileSharingResolver struct{ *Resolver }
type folderResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
