package graphQL

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.80

import (
	"context"
	"fmt"

	"github.com/BalkanID-University/vit-2026-capstone-internship-hiring-task-joel2607/models"
)

// ID resolves the id field for the DeduplicatedContent type.
// It returns the unique identifier of the deduplicated content.
func (r *deduplicatedContentResolver) ID(ctx context.Context, obj *models.DeduplicatedContent) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// CreatedAt resolves the createdAt field for the DeduplicatedContent type.
// It returns the timestamp indicating when the deduplicated content was first created.
func (r *deduplicatedContentResolver) CreatedAt(ctx context.Context, obj *models.DeduplicatedContent) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt resolves the updatedAt field for the DeduplicatedContent type.
// It returns the timestamp indicating when the deduplicated content was last updated.
func (r *deduplicatedContentResolver) UpdatedAt(ctx context.Context, obj *models.DeduplicatedContent) (string, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// ReferenceCount resolves the referenceCount field for the DeduplicatedContent type.
// It returns the number of files that reference this deduplicated content.
func (r *deduplicatedContentResolver) ReferenceCount(ctx context.Context, obj *models.DeduplicatedContent) (int32, error) {
	panic(fmt.Errorf("not implemented: ReferenceCount - referenceCount"))
}

// ID resolves the id field for the File type.
// It returns the unique identifier of the file.
func (r *fileResolver) ID(ctx context.Context, obj *models.File) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// CreatedAt resolves the createdAt field for the File type.
// It returns the timestamp indicating when the file was created.
func (r *fileResolver) CreatedAt(ctx context.Context, obj *models.File) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt resolves the updatedAt field for the File type.
// It returns the timestamp indicating when the file was last updated.
func (r *fileResolver) UpdatedAt(ctx context.Context, obj *models.File) (string, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// UserID resolves the userId field for the File type.
// It returns the unique identifier of the user who owns the file.
func (r *fileResolver) UserID(ctx context.Context, obj *models.File) (string, error) {
	panic(fmt.Errorf("not implemented: UserID - userId"))
}

// Size resolves the size field for the File type.
// It returns the size of the file in bytes.
func (r *fileResolver) Size(ctx context.Context, obj *models.File) (int32, error) {
	panic(fmt.Errorf("not implemented: Size - size"))
}

// DeduplicationID resolves the deduplicationId field for the File type.
// It returns the identifier of the deduplicated content associated with this file.
func (r *fileResolver) DeduplicationID(ctx context.Context, obj *models.File) (string, error) {
	panic(fmt.Errorf("not implemented: DeduplicationID - deduplicationId"))
}

// DownloadCount resolves the downloadCount field for the File type.
// It returns the number of times the file has been downloaded.
func (r *fileResolver) DownloadCount(ctx context.Context, obj *models.File) (int32, error) {
	panic(fmt.Errorf("not implemented: DownloadCount - downloadCount"))
}

// ParentFolderID resolves the parentFolderId field for the File type.
// It returns the identifier of the parent folder, or null if the file is in the root directory.
func (r *fileResolver) ParentFolderID(ctx context.Context, obj *models.File) (*string, error) {
	panic(fmt.Errorf("not implemented: ParentFolderID - parentFolderId"))
}

// ID resolves the id field for the FileSharing type.
// It returns the unique identifier of the file sharing record.
func (r *fileSharingResolver) ID(ctx context.Context, obj *models.FileSharing) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// CreatedAt resolves the createdAt field for the FileSharing type.
// It returns the timestamp indicating when the file was shared.
func (r *fileSharingResolver) CreatedAt(ctx context.Context, obj *models.FileSharing) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt resolves the updatedAt field for the FileSharing type.
// It returns the timestamp indicating when the file sharing record was last updated.
func (r *fileSharingResolver) UpdatedAt(ctx context.Context, obj *models.FileSharing) (string, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// FileID resolves the fileId field for the FileSharing type.
// It returns the unique identifier of the shared file.
func (r *fileSharingResolver) FileID(ctx context.Context, obj *models.FileSharing) (string, error) {
	panic(fmt.Errorf("not implemented: FileID - fileId"))
}

// SharedWithUserID resolves the sharedWithUserId field for the FileSharing type.
// It returns the unique identifier of the user with whom the file is shared.
func (r *fileSharingResolver) SharedWithUserID(ctx context.Context, obj *models.FileSharing) (string, error) {
	panic(fmt.Errorf("not implemented: SharedWithUserID - sharedWithUserId"))
}

// ID resolves the id field for the Folder type.
// It returns the unique identifier of the folder.
func (r *folderResolver) ID(ctx context.Context, obj *models.Folder) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// CreatedAt resolves the createdAt field for the Folder type.
// It returns the timestamp indicating when the folder was created.
func (r *folderResolver) CreatedAt(ctx context.Context, obj *models.Folder) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt resolves the updatedAt field for the Folder type.
// It returns the timestamp indicating when the folder was last updated.
func (r *folderResolver) UpdatedAt(ctx context.Context, obj *models.Folder) (string, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// UserID resolves the userId field for the Folder type.
// It returns the unique identifier of the user who owns the folder.
func (r *folderResolver) UserID(ctx context.Context, obj *models.Folder) (string, error) {
	panic(fmt.Errorf("not implemented: UserID - userId"))
}

// ParentFolderID resolves the parentFolderId field for the Folder type.
// It returns the identifier of the parent folder, or null if the folder is in the root directory.
func (r *folderResolver) ParentFolderID(ctx context.Context, obj *models.Folder) (*string, error) {
	panic(fmt.Errorf("not implemented: ParentFolderID - parentFolderId"))
}

// Register handles user registration.
// It accepts user registration details (username, email, password) and creates a new user account.
// Returns the newly created user object upon successful registration.
func (r *mutationResolver) Register(ctx context.Context, input models.RegisterInput) (*models.User, error) {
	user, err := r.AuthService.Register(input)
	if err != nil {
		return nil, err
	}
	return user, nil
}

// Login handles user authentication.
// It accepts a user's email and password, and if valid, returns an authentication response containing a token.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*models.AuthResponse, error) {
	token, user, err := r.AuthService.Login(email, password)
	if err != nil {
		return nil, err
	}
	return &models.AuthResponse{Token: token, User: user}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	user := ctx.Value("user")
	if user == nil {
		return nil, fmt.Errorf("access denied")
	}
	return user.(*models.User), nil
}

// ID resolves the id field for the User type.
// It returns the unique identifier of the user.
func (r *userResolver) ID(ctx context.Context, obj *models.User) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// CreatedAt resolves the createdAt field for the User type.
// It returns the timestamp indicating when the user account was created.
func (r *userResolver) CreatedAt(ctx context.Context, obj *models.User) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt resolves the updatedAt field for the User type.
// It returns the timestamp indicating when the user account was last updated.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *models.User) (string, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// StorageQuotaMb resolves the storageQuotaMB field for the User type.
// It returns the user's total storage quota in megabytes.
func (r *userResolver) StorageQuotaMb(ctx context.Context, obj *models.User) (int32, error) {
	panic(fmt.Errorf("not implemented: StorageQuotaMb - storageQuotaMB"))
}

// UsedStorageMb resolves the usedStorageMB field for the User type.
// It returns the amount of storage the user has consumed in megabytes.
func (r *userResolver) UsedStorageMb(ctx context.Context, obj *models.User) (int32, error) {
	panic(fmt.Errorf("not implemented: UsedStorageMb - usedStorageMB"))
}

// APIRateLimit resolves the apiRateLimit field for the User type.
// It returns the maximum number of API requests the user can make per minute.
func (r *userResolver) APIRateLimit(ctx context.Context, obj *models.User) (int32, error) {
	panic(fmt.Errorf("not implemented: APIRateLimit - apiRateLimit"))
}

// DeduplicatedContent returns DeduplicatedContentResolver implementation.
func (r *Resolver) DeduplicatedContent() DeduplicatedContentResolver {
	return &deduplicatedContentResolver{r}
}

// File returns FileResolver implementation.
func (r *Resolver) File() FileResolver { return &fileResolver{r} }

// FileSharing returns FileSharingResolver implementation.
func (r *Resolver) FileSharing() FileSharingResolver { return &fileSharingResolver{r} }

// Folder returns FolderResolver implementation.
func (r *Resolver) Folder() FolderResolver { return &folderResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type deduplicatedContentResolver struct{ *Resolver }
type fileResolver struct{ *Resolver }
type fileSharingResolver struct{ *Resolver }
type folderResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
