// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

// Response type for a successful login.
type AuthResponse struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type FileFilterInput struct {
	MimeTypes  []string `json:"mimeTypes,omitempty"`
	MinSize    *int32   `json:"minSize,omitempty"`
	MaxSize    *int32   `json:"maxSize,omitempty"`
	StartDate  *string  `json:"startDate,omitempty"`
	EndDate    *string  `json:"endDate,omitempty"`
	Tags       []string `json:"tags,omitempty"`
	UploaderID *string  `json:"uploaderID,omitempty"`
}

// Defines the mutations available in the API.
type Mutation struct {
}

type NewFolder struct {
	Name           string  `json:"name"`
	ParentFolderID *string `json:"parentFolderID,omitempty"`
}

// Defines the queries available in the API.
type Query struct {
}

// Input for the registration mutation.
type RegisterInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Root struct {
	Files   []*File   `json:"files,omitempty"`
	Folders []*Folder `json:"folders,omitempty"`
}

type UpdateFile struct {
	ID             string  `json:"id"`
	Name           *string `json:"name,omitempty"`
	ParentFolderID *string `json:"parentFolderID,omitempty"`
}

type UpdateFolder struct {
	ID             string  `json:"id"`
	Name           *string `json:"name,omitempty"`
	ParentFolderID *string `json:"parentFolderID,omitempty"`
}
