// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

// Response type for a successful login.
type AuthResponse struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

// Defines the queries available in the API.
type Mutation struct {
}

type Query struct {
}

// Input for the registration mutation.
type RegisterInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
