package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.80

import (
	"context"
	"fmt"

	"github.com/BalkanID-University/vit-2026-capstone-internship-hiring-task-joel2607/models"
)

// ID is the resolver for the id field.
func (r *deduplicatedContentResolver) ID(ctx context.Context, obj *models.DeduplicatedContent) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *deduplicatedContentResolver) CreatedAt(ctx context.Context, obj *models.DeduplicatedContent) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *deduplicatedContentResolver) UpdatedAt(ctx context.Context, obj *models.DeduplicatedContent) (string, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// ReferenceCount is the resolver for the referenceCount field.
func (r *deduplicatedContentResolver) ReferenceCount(ctx context.Context, obj *models.DeduplicatedContent) (int32, error) {
	panic(fmt.Errorf("not implemented: ReferenceCount - referenceCount"))
}

// ID is the resolver for the id field.
func (r *fileResolver) ID(ctx context.Context, obj *models.File) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *fileResolver) CreatedAt(ctx context.Context, obj *models.File) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *fileResolver) UpdatedAt(ctx context.Context, obj *models.File) (string, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// UserID is the resolver for the userId field.
func (r *fileResolver) UserID(ctx context.Context, obj *models.File) (string, error) {
	panic(fmt.Errorf("not implemented: UserID - userId"))
}

// Size is the resolver for the size field.
func (r *fileResolver) Size(ctx context.Context, obj *models.File) (int32, error) {
	panic(fmt.Errorf("not implemented: Size - size"))
}

// DeduplicationID is the resolver for the deduplicationId field.
func (r *fileResolver) DeduplicationID(ctx context.Context, obj *models.File) (string, error) {
	panic(fmt.Errorf("not implemented: DeduplicationID - deduplicationId"))
}

// DownloadCount is the resolver for the downloadCount field.
func (r *fileResolver) DownloadCount(ctx context.Context, obj *models.File) (int32, error) {
	panic(fmt.Errorf("not implemented: DownloadCount - downloadCount"))
}

// ParentFolderID is the resolver for the parentFolderId field.
func (r *fileResolver) ParentFolderID(ctx context.Context, obj *models.File) (*string, error) {
	panic(fmt.Errorf("not implemented: ParentFolderID - parentFolderId"))
}

// ID is the resolver for the id field.
func (r *fileSharingResolver) ID(ctx context.Context, obj *models.FileSharing) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *fileSharingResolver) CreatedAt(ctx context.Context, obj *models.FileSharing) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *fileSharingResolver) UpdatedAt(ctx context.Context, obj *models.FileSharing) (string, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// FileID is the resolver for the fileId field.
func (r *fileSharingResolver) FileID(ctx context.Context, obj *models.FileSharing) (string, error) {
	panic(fmt.Errorf("not implemented: FileID - fileId"))
}

// SharedWithUserID is the resolver for the sharedWithUserId field.
func (r *fileSharingResolver) SharedWithUserID(ctx context.Context, obj *models.FileSharing) (string, error) {
	panic(fmt.Errorf("not implemented: SharedWithUserID - sharedWithUserId"))
}

// ID is the resolver for the id field.
func (r *folderResolver) ID(ctx context.Context, obj *models.Folder) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *folderResolver) CreatedAt(ctx context.Context, obj *models.Folder) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *folderResolver) UpdatedAt(ctx context.Context, obj *models.Folder) (string, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// UserID is the resolver for the userId field.
func (r *folderResolver) UserID(ctx context.Context, obj *models.Folder) (string, error) {
	panic(fmt.Errorf("not implemented: UserID - userId"))
}

// ParentFolderID is the resolver for the parentFolderId field.
func (r *folderResolver) ParentFolderID(ctx context.Context, obj *models.Folder) (*string, error) {
	panic(fmt.Errorf("not implemented: ParentFolderID - parentFolderId"))
}



// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *models.User) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *models.User) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *models.User) (string, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// StorageQuotaMb is the resolver for the storageQuotaMB field.
func (r *userResolver) StorageQuotaMb(ctx context.Context, obj *models.User) (int32, error) {
	panic(fmt.Errorf("not implemented: StorageQuotaMb - storageQuotaMB"))
}

// UsedStorageMb is the resolver for the usedStorageMB field.
func (r *userResolver) UsedStorageMb(ctx context.Context, obj *models.User) (int32, error) {
	panic(fmt.Errorf("not implemented: UsedStorageMb - usedStorageMB"))
}

// APIRateLimit is the resolver for the apiRateLimit field.
func (r *userResolver) APIRateLimit(ctx context.Context, obj *models.User) (int32, error) {
	panic(fmt.Errorf("not implemented: APIRateLimit - apiRateLimit"))
}

// DeduplicatedContent returns DeduplicatedContentResolver implementation.
func (r *Resolver) DeduplicatedContent() DeduplicatedContentResolver {
	return &deduplicatedContentResolver{r}
}

// File returns FileResolver implementation.
func (r *Resolver) File() FileResolver { return &fileResolver{r} }

// FileSharing returns FileSharingResolver implementation.
func (r *Resolver) FileSharing() FileSharingResolver { return &fileSharingResolver{r} }

// Folder returns FolderResolver implementation.
func (r *Resolver) Folder() FolderResolver { return &folderResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type deduplicatedContentResolver struct{ *Resolver }
type fileResolver struct{ *Resolver }
type fileSharingResolver struct{ *Resolver }
type folderResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
